services:
  # front-end's web-app
  shiny:
    # build from Dockerfile in current local directory
    build: .
    ports: 
      - "3838:3838"
    # bind mount to reflect saved code changes, no need to restart container for each revision 
    # source is local directory
    # target is container directory with R scripts 
    volumes:
      - type: bind
        source: .
        target: /home/app

  # Flask app API
  flask:
    # Build from files and Dockerfile in /api directory
    build: ./api
    ports:
      - "5000:5000"
    # To allow reference to elasticsearch container in flask app
    environment:
    - ELASTICSEARCH_HOST=elasticsearch
  
  # Document store
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      - discovery.type=single-node
    # For persistent data in the document store
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  data01:
    driver: local
  
