services:
  # front-end's web-app
  shiny:
    # built from Dockerfile found in same directory
    build: .
    # exposed port
    ports: 
      - "3838:3838"
    # bind mount to reflect saved code changes, no need to restart container 
    # source is local directory
    # target is container directory with scripts
    volumes:
      - type: bind
        source: .
        target: /home/app

  flask:
    build: ./api
    ports:
      - "5000:5000"
    environment:
    - ELASTICSEARCH_HOST=elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      - discovery.type=single-node
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  data01:
    driver: local
  
