services:
  shiny:
    build: .
    ports: 
      - "3838:3838"

  flask:
    build: ./api

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      - discovery.type=single-node
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  volumes:
    data01:
      driver: local
  